config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#home"
  resources :spas do
    resources :bookings, only: ['new', 'create']
  end

  resources :bookings, only: ['index', 'edit']
  resources :dashboards, only: ['index', 'edit']
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :spa
  has_one :review
  validates :start_date, :end_date, presence: true
  validate :booking_dates_verify

  private

  def booking_dates_verify
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :rating, presence: true
end

app/models/spa.rb
class Spa < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_one_attached :photo
  has_many :reviews, through: :bookings
  validates :name, length: { minimum: 2 }, presence: true, uniqueness: { scope: :address, message: "This spa already exists for this address" }
  validates :address, length: { minimum: 4 }, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :category, inclusion: { in: %w(jacuzzi hammam sauna) }
  CATEGORIES = ["jacuzzi", "hammam", "sauna"]

  def average_rating
    if reviews.count.positive?
      sum = 0
      reviews.each do |review|
        sum += review.rating
      end
      sum / reviews.count
    else
      0
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :spas
  has_many :bookings
  has_many :reviews, through: :bookings
  has_many :bookings_as_owner, through: :spas, source: :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_spa, only: ['new', 'create']

  def index
    @spas = policy_scope(Spa)
  end

  # Create a new booking shell to provide to the form
  # Booking dates are sent to flatpickr to block unavailable days
  def new
    @booking = Booking.new
    @bookings       = @spa.bookings
    @bookings_dates = @bookings.map do |booking|
      {
        from: booking.start_date,
        to:   booking.end_date
      }
    end
    authorize @booking
  end

  # Creation of the booking based on data submitted via the form
  # Start date and end date have been added manually due to flatpickr gem
  def create
    selected_dates = booking_params['start_date'].split(" au ")
    @booking = Booking.new
    @booking.user = current_user
    @booking.spa = @spa
    @booking.status = "en attente"
    @booking.start_date = selected_dates[0]
    @booking.end_date = selected_dates[1]
    authorize @booking
    if @booking.save
      redirect_to bookings_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  # Sets the user that is currently logged in
  def set_spa
    @spa = Spa.find(params[:spa_id])
  end

  # Sstrong params
  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :status)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def index
    @spas = policy_scope(Spa).where(user: current_user)
    @bookings = current_user.bookings_as_owner.order("id ASC")
  end

  # Edit the booking to change its status
  def edit
    @booking = Booking.find(params['id'])
    authorize @booking
    if @booking.update(status: params['status'])
      redirect_to dashboards_path
    else
      render "/dashboards", status: :unprocessable_entity
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @spas_last = Spa.last(6)
  end
end

app/controllers/spas_controller.rb
class SpasController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    @spas = policy_scope(Spa)
    @spas = @spas.where("address ILIKE ?", "%#{params[:query]}%") if(params[:query].present?)
    @spas = @spas.where("category ILIKE ?", "%#{params[:category]}%") if(params[:category].present?)


    # a changer par @spas
    @markers = @spas.geocoded.map do |spa|
    {
      lat: spa.latitude,
      lng: spa.longitude,
      info_window: render_to_string(partial: "info_window", locals: {spa: spa}),
      image_url: helpers.asset_url("lotus.png")
    }
  end

    # if(params['query'].present?)
    #   @spas = policy_scope(Spa.where("address ILIKE ?", "%#{params[:query]}%"))
    # else
    #   # Ici, on vise l'ensemble des spa (Spa.all mais avec le pundit)
    # end

    # Array des 5 plus populaires mélangés pour affichage dans l'index :
    @spas_sorted = Spa.all.sort_by { |spa_to_sort| spa_to_sort.average_rating }.reverse.slice(0..4).sample(3).sort_by { |spa_to_sort| spa_to_sort.average_rating }.reverse
  end

  def show
    @spa = Spa.find(params[:id])
    @booking = Booking.new
    @bookings       = @spa.bookings
    @bookings_dates = @bookings.map do |booking|
      {
        from: booking.start_date,
        to:   booking.end_date
      }
    end
    @markers = [{
      lat: @spa.latitude,
      lng: @spa.longitude,
      info_window: render_to_string(partial: "info_window", locals: {spa: @spa}),
      image_url: helpers.asset_url("lotus.png")
    }]
    authorize @spa
  end

  def new
    @spa = Spa.new
    authorize @spa
  end

  def create
    @spa = Spa.new(spa_params)
    @spa.user_id = current_user.id
    authorize @spa
    if @spa.save
      redirect_to spa_path(@spa)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @spa = Spa.find(params[:id])
    authorize @spa
  end

  def update
    @spa = Spa.find(params[:id])
    authorize @spa
    if @spa.update(spa_params)
      redirect_to spa_path(@spa)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @spa = Spa.find(params[:id])
    @spa.destroy
    authorize @spa
    redirect_to spas_path, status: :see_other
  end

  private

  def spa_params
    params.require(:spa).permit(:name, :address, :category, :price_per_hour, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container text-center mt-5 booking-card">
  <h1 class="my-5">Réservation(s) en cours</h1>
  <div class="row">
    <% @spas.each do |spa| %>
      <% unless spa.bookings.empty? %>
        <% spa.bookings.each do |booking| %>
          <% if booking.user_id == current_user.id %>
            <div class="col-sm-12 col-md-12 col-lg-12 <%= spa.bookings.count == 1 ? "col-xl-12 p-5" : "col-xl-6" %> mb-5">
              <div class="dashboard-card-trip">
                <%= cl_image_tag spa.photo.key, crop: :fill %>
                <h2 class="text-center mt-2 dashboard-card-title"><%= spa.name %></h2>
                <div class="dashboard-card-trip-infos">
                  <div>
                    <p><strong>Date de début</strong> : <%= booking.start_date %></p>
                    <p><strong>Date de fin</strong> : <%= booking.end_date %></p>
                  </div>
                  <div class="mt-2">
                    <p>
                      <strong>Statut</strong> : <%= booking.status %>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div data-controller="flatpickr">
  <% if current_user.id != @spa.user_id  %>
    <h1 > Réservez votre spa! </h1>
    <div id='flat-booking-dates'>
        <%= simple_form_for([:spa, @booking]) do |f| %>
            <%= f.input :start_date, as: :string, label: "Sélectionnez vos dates", input_html: { id: "range_start", class: "d-none", data: { action: "change->flatpickr#handleChange", 'flatpickr-target' => 'inputStartDate' } } %>
            <%= hidden_field_tag f.input :end_date, as: :date, html5: true, input_html: { id: "range_end", class: "d-none", data: { action: "change->flatpickr#handleChange", target: 'flatpickr.inputEndDate' } } %>
            <p>Nombre de jours au total : <span data-flatpickr-target="days"></span></p>
            <%= f.submit %>
        <% end %>
    </div>
    <div data-flatpickr-target="bookingForm"
      data-bookings="<%= @bookings_dates.to_json %>">
    </div>
  <% else %>
    <p>Vous n'êtes pas autorisé à visiter cette page !</p>
  <% end %>

</div>

app/views/dashboards/index.html.erb
<div class="container-fluid text-center mt-5 booking-card">
  <h1 class="my-5">Mes locations</h1>
  <div class="row">
    <% @bookings.each do |booking| %>
      <% unless @bookings.empty? %>
        <div class="col-sm-12 col-md-12 <%= @bookings.count == 1 ? "col-xl-12 p-5" : "col-xl-6" %> mb-5">
          <div class="dashboard-card-trip">
            <%= cl_image_tag booking.spa.photo.key, crop: :fill %>
            <h2 class="text-center mt-2 dashboard-card-title"><%= booking.spa.name %></h2>
            <div class="dashboard-card-trip-infos">
              <div>
                <p><strong>Date de début</strong> : <%= booking.start_date %></p>
                <p><strong>Date de fin</strong> : <%= booking.end_date %></p>
                <p><strong>Réservé par</strong> : <%= booking.user.first_name %> <%= booking.user.last_name %></p>
              </div>
              <div class="mt-2">
                <p>
                  <strong>Statut</strong> : <%= booking.status %>
                </p>
                <% if booking.status == "accepté" %>
                  <%= link_to 'Annuler', edit_dashboard_path(booking, {status: "en attente"}), class: "btn btn-secondary" %>
                  <%= link_to 'Refuser', edit_dashboard_path(booking, {status: "refusé"}), class: "btn btn-danger text-white"  %>
                <% elsif booking.status == "refusé" %>
                  <%= link_to 'Annuler', edit_dashboard_path(booking, {status: "en attente"}), class: "btn btn-secondary" %>
                  <%= link_to 'Valider', edit_dashboard_path(booking, {status: "accepté"}), class: "btn btn-primary" %>
                <% else %>
                  <%= link_to 'Valider', edit_dashboard_path(booking, {status: "accepté"}), class: "btn btn-primary" %>
                  <%= link_to 'Refuser', edit_dashboard_path(booking, {status: "refusé"}), class: "btn btn-danger text-white"  %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
<script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
<html>
  <head>
    <title>Airspas</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://kit.fontawesome.com/91101f945a.js" crossorigin="anonymous"></script>
    <%= favicon_link_tag asset_path('lotus.png') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <div class="fix_footer_down">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://coquillade.fr/_novaimg/4698289-1490140_70_994_4419_1177_2200_586.jpg);">
    <h1>Venez vous détendre dans notre sélection de SPA faite pour vous!</h1>
    <div class="btn-banner">
      <a class="btn btn-light mt-5 rounded-pill" href="/spas">Réservez votre moment de détente</a>
    </div>
</div>

<div class="container">
  <div id="recent">
    <h4>Ajouts récents</h4>
    <div class="recent_cards_expo">
      <div class="recent_cards_cards" id="card_home_1">
        <%= link_to spa_path(@spas_last[0]) do %>
          <%= cl_image_tag @spas_last[0].photo.key, crop: :fill %>
          <p><%= @spas_last[0].name %></p>
        <% end %>
      </div>

      <div class="recent_cards_wrap">
        <div class="recent_cards_cards" id="card_home_2">
          <%= link_to spa_path(@spas_last[1]) do %>
            <%= cl_image_tag @spas_last[1].photo.key, crop: :fill %>
            <p><%= @spas_last[1].name %></p>
          <% end %>
        </div>
        <div class="recent_cards_cards" id="card_home_3">
          <%= link_to spa_path(@spas_last[2]) do %>
            <%= cl_image_tag @spas_last[2].photo.key, crop: :fill %>
            <p><%= @spas_last[2].name %></p>
          <% end %>
        </div>
      </div>

      <div class="recent_cards_cards" id="card_home_4">
        <%= link_to spa_path(@spas_last[3]) do %>
          <%= cl_image_tag @spas_last[3].photo.key, crop: :fill %>
          <p><%= @spas_last[3].name %></p>
        <% end %>
      </div>

      <div class="recent_cards_wrap">
        <div class="recent_cards_cards" id="card_home_5">
          <%= link_to spa_path(@spas_last[4]) do %>
            <%= cl_image_tag @spas_last[4].photo.key, crop: :fill %>
            <p><%= @spas_last[4].name %></p>
          <% end %>
        </div>
        <div class="recent_cards_cards" id="card_home_6">
          <%= link_to spa_path(@spas_last[5]) do %>
            <%= cl_image_tag @spas_last[5].photo.key, crop: :fill %>
            <p><%= @spas_last[5].name %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-primary alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="custom-footer">
  <div class="container">
    <div class="custom-container">
      <!--<div class="custom-container-block footer-police-size">
        <a href="#">Conditions d'utilisation</a>
        <a href="#">Gestion des cookies</a>
        <a href="#">Comment fonctionne le site</a>
        <a href="#">Contactez-nous</a>
      </div>-->
      <div class="custom-container-block-network">
        <span class="footer-police-size">Nos réseaux</span>
        <div>
          <a href="#"><img src="https://cdn-icons-png.flaticon.com/512/87/87390.png" alt="Instagram" class="custom-container-block-img"></a>
          <a href="#"><img src="https://cdn-icons-png.flaticon.com/512/733/733635.png" alt="Twitter" class="custom-container-block-img"></a>
          <a href="#"><img src="https://cdn-icons-png.flaticon.com/512/1384/1384021.png" alt="Facebook" class="custom-container-block-img"></a>
          <a href="#"><img src="https://cdn-icons-png.flaticon.com/512/5969/5969008.png" alt="TikTok" class="custom-container-block-img"></a>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/spas/_info_window.html.erb
<h2><%= spa.name %></h2>
<p><%= spa.address %></p>

app/views/spas/edit.html.erb
<div class="container" style="margin-top: 30px">
  <h4>Editer votre spa</h4>
  <p>Modifiez les informations à mettre à jour</p>

  <%= simple_form_for(@spa) do |f| %>
    <%= f.input :name, label: "Nom" %>
    <%= f.input :address, label: "Adresse" %>
    <%= f.input :category, collection: Spa::CATEGORIES, label: "Catégorie" %>
    <%= f.input :price_per_hour, label: "Prix par heure €" %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Editer le SPA" %>
  <% end %>
</div>

app/views/spas/index.html.erb
<%# Top index  %>
<div class="container mb-5">
  <div class="top_index">
    <div class="d-flex justify-content-between align-items-center">
      <div>
        <h4>Trouvez le spa de vos rêves</h4>
        <p>Parmis les plus beaux jacuzzis, hammams et saunas, partout en France !</p>
        <div class="filter">
          <h5> Filtres </h5>
          <ul>
            <%= link_to spas_path(query: params[:query], category: "Hammam") do %>
              <li class="filter_button <%= "active" if params[:category] == "Hammam" %>">Hammam</li>
            <% end %>
            <%= link_to spas_path(query: params[:query], category: "Sauna") do %>
              <li class="filter_button <%= "active" if params[:category] == "Sauna" %>">Sauna</li>
            <% end %>
            <%= link_to spas_path(query: params[:query], category: "Jacuzzi") do %>
              <li class="filter_button <%= "active" if params[:category] == "Jacuzzi" %>">Jacuzzi</li>
            <% end %>
            <%= link_to spas_path do %>
              <li class="filter_button">Sans filtre</li>
            <% end %>
          </ul>
        </div>
        <div class="info">
          <img src="https://cdn-icons-png.flaticon.com/512/665/665049.png" alt="pictogramme-information">
          <span>Plus de <%= @spas.length %> spas disponibles dans votre selection !</span>
        </div>
      </div>
      <div>
        <div class="research_tab">
          <div class="research_symbol"> <img src="https://cdn-icons-png.flaticon.com/512/7472/7472700.png" alt="research_pin_symbol"> </div>
            <%= form_with url: spas_path, method: :get, class: "d-flex" do %>
              <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Trouvez un spa"%>
              <% request.params.slice("category").each do |key, value| %>
                <%= hidden_field_tag key, value %>
              <% end %>
              <%= submit_tag "Chercher", class: "btn btn-secondary" %>
            <% end %>
          </div>
          <div style="width: 100%; height: 150px; "data-controller="map" data-map-markers-value="<%= @markers.to_json %>" data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
        </div>
    </div>
  </div>

  <div class="d-flex justify-content-between">
    <article>
      <h4>La selection <%= link_to "(+ Ajouter votre SPA)", new_spa_path if policy(Spa).new? %></h4>
      <div class="grid">
        <% @spas.each do |spa| %>
          <div class="card-selection">
            <%= link_to spa_path(spa) do %>
              <%= cl_image_tag spa.photo.key, crop: :fill %>
              <div class="card-selection-header">
                <h5><%= spa.name %></h5>
                <% if spa.reviews.count.positive? %>
                  <div class="star_rating" id="star_rating_selection">
                    <div class="stars-black">
                      <i class="fa-sharp fa-solid fa-star"></i>
                      <i class="fa-sharp fa-solid fa-star"></i>
                      <i class="fa-sharp fa-solid fa-star"></i>
                      <i class="fa-sharp fa-solid fa-star"></i>
                      <i class="fa-sharp fa-solid fa-star"></i>
                      <div class="stars-gold" style="width: <%= spa.average_rating/5*100 %>%">
                        <i class="fa-sharp fa-solid fa-star"></i>
                        <i class="fa-sharp fa-solid fa-star"></i>
                        <i class="fa-sharp fa-solid fa-star"></i>
                        <i class="fa-sharp fa-solid fa-star"></i>
                        <i class="fa-sharp fa-solid fa-star"></i>
                      </div>
                    </div>
                    <p><%= spa.average_rating.round(1) %></p>
                  </div>
                <% end %>
              </div>
              <span>A partir de <strong><%= spa.price_per_hour %> €</strong></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </article>

    <aside>
      <div class="d-flex justify-content-between aside_title">
        <h4>Les plus populaires</h4>
        <h4>&#9733;</h4>
      </div>
      <div class="aside_grid">
        <% @spas_sorted.each do |spa| %>
          <div class="card-aside">
            <%= link_to spa_path(spa) do %>
                <%= cl_image_tag spa.photo.key, crop: :fill %>
                <div class="description">
                  <div>
                    <h4><%= spa.name %></h4>
                    <p>A partir de <strong><%= spa.price_per_hour %> €</strong></p>
                    <% if spa.reviews.count.positive? %>
                      <div class="star_rating" id="star_rating_popular">
                        <div class="stars-black">
                          <i class="fa-sharp fa-solid fa-star"></i>
                          <i class="fa-sharp fa-solid fa-star"></i>
                          <i class="fa-sharp fa-solid fa-star"></i>
                          <i class="fa-sharp fa-solid fa-star"></i>
                          <i class="fa-sharp fa-solid fa-star"></i>
                          <div class="stars-gold" style="width: <%= spa.average_rating/5*100 %>%">
                            <i class="fa-sharp fa-solid fa-star"></i>
                            <i class="fa-sharp fa-solid fa-star"></i>
                            <i class="fa-sharp fa-solid fa-star"></i>
                            <i class="fa-sharp fa-solid fa-star"></i>
                            <i class="fa-sharp fa-solid fa-star"></i>
                          </div>
                        </div>
                        <p><%= spa.average_rating.round(1) %></p>
                      </div>
                    <% end %>
                  </div>
                </div>
            <% end %>
          </div>
        <% end %>
			</div>
    </aside>
  </div>
</div>

app/views/spas/new.html.erb
<div class="container" style="margin-top: 30px">
  <h4>Nouveau spa</h4>
  <p>Entrez les informations de votre spa pour le mettre ligne</p>

  <%= simple_form_for(@spa) do |f| %>
    <%= f.input :name, label: "Nom" %>
    <%= f.input :address, label: "Adresse" %>
    <%= f.input :category, collection: Spa::CATEGORIES, label: "Catégorie" %>
    <%= f.input :price_per_hour, label: "Prix par heure €" %>
    <%= f.input :photo, as: :file %>
    <%= f.submit 'Créer le SPA' %>
  <% end %>
</div>

app/views/spas/show.html.erb
<div class="fix_footer_down">


<div class="container mt-4 mb-4 bg-white resize">
  <div class="resize-upperblock">
    <div>
      <%= cl_image_tag @spa.photo.key, crop: :fill, class:"img-spa text-center" %>
    </div>
    <div class="show-map">
      <div style="width: 494px; height: 350px;"
        data-controller="map"
        data-map-markers-value="<%= @markers.to_json %>"
        data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
        data-map-fly-value=true>
      </div>
    </div>
  </div>
  <div class="resize-bottom-block">
    <div class="card-info">
      <h5 class="title">
        <%= @spa.name.capitalize %>
        <% if policy(@spa).edit? %> <%= link_to image_tag("https://cdn-icons-png.flaticon.com/512/1827/1827951.png", class: "picto"), edit_spa_path(@spa) %> <% end %>
        <% if policy(@spa).destroy? %> <span class="pipe">|</span> <%= link_to image_tag("https://cdn-icons-png.flaticon.com/512/1214/1214428.png", class: "picto"), spa_path(@spa), data: {turbo_method: :delete, turbo_confirm: "Etes-vous sûr ?"} %><% end %>
      </h5>
      <p><img src="https://cdn-icons-png.flaticon.com/512/7472/7472700.png" alt="localisation pictogramme" style="width: 16px"><%= @spa.address %></p>
      <% if @spa.reviews.count.positive? %>
        <div class="star_rating" id="star_rating_show">
          <div class="stars-black">
            <i class="fa-sharp fa-solid fa-star"></i>
            <i class="fa-sharp fa-solid fa-star"></i>
            <i class="fa-sharp fa-solid fa-star"></i>
            <i class="fa-sharp fa-solid fa-star"></i>
            <i class="fa-sharp fa-solid fa-star"></i>
            <div class="stars-gold" style="width: <%= @spa.average_rating/5*100 %>%">
              <i class="fa-sharp fa-solid fa-star"></i>
              <i class="fa-sharp fa-solid fa-star"></i>
              <i class="fa-sharp fa-solid fa-star"></i>
              <i class="fa-sharp fa-solid fa-star"></i>
              <i class="fa-sharp fa-solid fa-star"></i>
            </div>
          </div>
          <p><%= @spa.average_rating.round(1) %> selon <%= @spa.reviews.count %> avis</p>
        </div>
      <% end %>
      <p><%= @spa.price_per_hour %>€ pour une heure</p>
      <p>Description :</p>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae, iste sed ea quibusdam quidem vel perspiciatis magni alias fuga, eum unde enim doloribus ullam neque deserunt tenetur ducimus officia at.</p>
      <div class="calendar">
        <div data-controller="flatpickr">
          <% if current_user.id != @spa.user_id  %>
            <div id='flat-booking-dates'>
                <%= simple_form_for([@spa, @booking]) do |f| %>
                  <%= f.input :start_date, as: :string, label: "Sélectionnez vos dates", input_html: { id: "range_start", class: "d-none", data: { action: "change->flatpickr#handleChange", 'flatpickr-target' => 'inputStartDate' } } %>
                  <%= hidden_field_tag f.input :end_date, as: :date, html5: true, input_html: { id: "range_end", class: "d-none", data: { action: "change->flatpickr#handleChange", target: 'flatpickr.inputEndDate' } } %>
                  <p>Nombre de jours au total : <span data-flatpickr-target="days"></span></p>
                  <%= f.button :submit, 'Réservez votre spa!', class: 'btn btn-secondary' %>
                <% end %>
            </div>
            <div data-flatpickr-target="bookingForm"
              data-bookings="<%= @bookings_dates.to_json %>">
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>